# Generated by Django 4.2.8 on 2024-01-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.CharField(max_length=140),
        ),
    ]
